name: dotnet format

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Install format tool
        run: dotnet tool install -g dotnet-format

      - name: check out code
        uses: actions/checkout@v2

      - name: dotnet format
        run: dotnet-format "./src/" --folder --check