name: public

on:
  push:

jobs:
  build:
    runs-on: windows
    steps:
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Echo version
        run: echo ${{ steps.get_version.outputs.VERSION }}

      # - name: Pack
      #   run: dotnet pack -v normal --include-symbols --configuration Release -p:PackageVersion=1.2.3 src/Napoli.OpenTelemetryExtensions